#!/usr/bin/env python3
"""summarize_report.py — aggregate all a11y-lint JSON outputs into one report.

Reads: output/a11y-lint/*.json (produced by the 12 tools in this suite)
Writes: output/a11y-lint/REPORT.md and prints a console summary.
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent.parent / "output" / "a11y-lint"

SECTION_ORDER = [
    ("contrast.json", "1. wcag-contrast — Color contrast (WCAG AA/AAA)", lambda d: f"{d['checked']} unique fg/bg pairs checked; **{len(d['failures'])} fail WCAG AA**" + (f"\n\nWorst offenders:\n\n| Ratio | Selector | FG | BG | File |\n|---|---|---|---|---|\n" + "\n".join(f"| {r['ratio']} | `{r['selector'][:40]}` | {r['fg']} | {r['bg']} | {r['file']} |" for r in d["failures"][:10]) if d["failures"] else "")),
    ("direction.json", "10. direction — RTL/LTR adaptability", lambda d: f"RTL content files: {len(d['rtlContentFiles'])}; lang/dir issues: {len(d['langDirIssues'])}" + ("\n\n" + "\n".join(f"- ⚠️ {i['file']}: {i['issue']}" for i in d["langDirIssues"]) if d["langDirIssues"] else "\n\n✅ No lang/dir mismatches found.")),
    ("colorblind.json", "3. color-blind — CVD simulation of state colors", lambda d: f"{d['stateTokensChecked']} semantic state tokens; **{len(d['confusions'])} potential confusions** under protanopia/deuteranopia/tritanopia/achromatopsia" + ("\n\n" + "\n".join(f"- {c['pair']} → indistinguishable under `{c['type']}` (distance {c['distance']})" for c in d["confusions"][:10]) if d["confusions"] else "\n\n✅ All state-color pairs remain distinguishable.")),
    ("readability.json", "4. textstat — Readability (grade level)", lambda d: f"{d['filesScored']} content files scored; **{len(d['flaggedAbove8thGrade'])} above grade {d['gradeLimit']}**" + ("\n\n" + "\n".join(f"- `{f['file']}` — Flesch-Kincaid grade {f['fkGrade']}, Gunning Fog {f['gunningFog']}" for f in d["flaggedAbove8thGrade"][:15]) if d["flaggedAbove8thGrade"] else "\n\n✅ All content at or below 8th-grade reading level.")),
    ("web-vitals.json", "5. web-vitals — Performance adaptability (CLS/LCP/INP/FCP/TTFB)", lambda d: f"{d['pagesMeasured']} pages measured; {d.get('pagesWithPoorMetrics', '?')} with poor metric(s)" + "\n\n" + "\n".join(f"- `{r['route']}`: " + ", ".join(f"{k}={round(v['value'],1)} ({v.get('rating') or 'n/a'})" for k, v in r.get("metrics", {}).items()) if r.get("metrics") else f"- `{r['route']}`: {r.get('error', 'no metrics')}" for r in d["results"][:20])),
    ("a11ycss.json", "6. a11y.css — CSS-injected visual warnings", lambda d: f"{d['filesChecked']} HTML files injected & parsed; **{d['totalFlagged']} flags**" + "\n\n" + "\n".join(f"- `{r['file']}`: {r['flaggedElements']} flagged element(s)" for r in d["results"] if r["flaggedElements"]) ),
    ("prose.json", "7. write-good — Prose clarity (passive voice, weasel words…)", lambda d: f"{d['filesChecked']} files, **{d['totalSuggestions']} style suggestions**" + "\n\n" + "\n".join(f"- `{r['file']}`: {r['totalSuggestions']} suggestions ({', '.join(f'{k}×{v}' for k, v in list(r['byType'].items())[:4])})" for r in d["results"][:15] if r["totalSuggestions"])),
    ("inclusive-language.json", "8. alex — Inclusive language scan", lambda d: f"**{d['totalFindings']} findings across {d['filesWithFlags']} files**" + "\n\n" + "\n".join(f"- `{r['file']}`: {r['count']} flag(s) — e.g. “{(r['messages'][0]['reason'] if r.get('messages') else '?')}”" for r in d["results"] if r.get("count"))),
    ("jsx-a11y.json", "10. eslint-plugin-jsx-a11y — Component-level a11y lint", lambda d: f"{d['filesChecked']} files linted ({d['note']}); **{d['totalErrors']} errors**" + "\n\n" + "\n".join(f"- `{r['file']}`: {r['errors']} error(s) — {', '.join(sorted({m['rule'].split('/')[-1] for m in r['messages'] if m['rule']}))}" for r in d["results"] if r["errors"])[:4000]),
    ("html-validate.json", "11. html-validate — HTML validity & semantics", lambda d: f"{d['filesChecked']} files checked; **{d['totalErrors']} errors**" + "\n\n" + "\n".join(f"- `{r['file']}`: {r['errors']} errors / {r['warnings']} warnings — {', '.join(sorted({str(m['ruleId']) for m in r['messages'] if m['severity']==2}))}" for r in d["results"] if r["errors"])),
    ("i18n-hardcoded.json", "12. i18next-scanner — Hardcoded string / i18n coverage", lambda d: f"{d['filesScanned']} source files scanned; **{d['filesWithHardcodedStrings']} files contain hardcoded UI strings** ({d['totalHardcodedSamples']} samples); translated keys discovered: {d['translatedKeysDiscovered']}"),
]


def main():
    lines = ["# Accessibility / Readability / Adaptability Lint Report", "",
             "Generated by `scripts/a11y_lint/run_all` using 12 sandbox-friendly tools:",
             "wcag-contrast, direction, color-blind, textstat, web-vitals, a11y.css,",
             "write-good, alex, pyphen, eslint-plugin-jsx-a11y, html-validate, i18next-scanner.",
             ""]
    missing = []
    for fname, title, render in SECTION_ORDER:
        p = OUT / fname
        lines.append(f"## {title}")
        lines.append("")
        if p.exists():
            try:
                lines.append(render(json.loads(p.read_text(encoding="utf-8"))))
            except Exception as e:  # noqa: BLE001
                lines.append(f"_failed to render: {e}_")
        else:
            lines.append("_not generated yet_")
            missing.append(fname)
        lines.append("")

    hp = OUT / "hyphenation.css"
    lines.append("## 9. pyphen — Hyphenation rules")
    lines.append("")
    lines.append(f"Generated CSS snippet: `output/a11y-lint/{hp.name}` ({'present' if hp.exists() else 'missing'}) — adds `hyphens:auto`, `overflow-wrap` guards and mobile column rules.")
    lines.append("")
    (OUT / "REPORT.md").write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(l for l in lines if l.startswith("#") or l.startswith("**") or "fail" in l.lower() or "error" in l.lower()))
    print(f"\nFull report: {OUT / 'REPORT.md'}")
    if missing:
        print(f"(missing outputs: {', '.join(missing)})")


if __name__ == "__main__":
    main()
