const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:390,height:844},colorScheme:'light',serviceWorkers:'block',reducedMotion:'reduce'});
 await context.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:8765/')?r.continue():r.abort());
 const page=await context.newPage();const passed=[];
 for(const route of ['index.html','book.html','blog/index.html','tools/guided-breathing.html']){
  console.log('Testing '+route);
  await page.goto('http://127.0.0.1:8765/'+route,{waitUntil:'load'});
  await page.locator('#burgerMenuBtn').click();
  assert.equal(await page.locator('#burgerMenuBtn').getAttribute('aria-expanded'),'true');
  assert.equal(await page.locator('main').evaluate(e=>e.inert),true);
  assert.equal(await page.locator('.close-mobile-menu').evaluate(e=>e===document.activeElement),true);
  await page.keyboard.press('Shift+Tab');
  assert.equal(await page.evaluate(()=>!!document.activeElement.closest('#mobile-nav-panel')),true);
  await page.keyboard.press('Tab');
  assert.equal(await page.locator('.close-mobile-menu').evaluate(e=>e===document.activeElement),true);
  await page.locator('.mobile-nav-tree-parent').first().click();
  assert.equal(await page.locator('.mobile-nav-tree-parent').first().getAttribute('aria-expanded'),'true');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('main').evaluate(e=>e.inert),false);
  assert.equal(await page.locator('#burgerMenuBtn').evaluate(e=>e===document.activeElement),true);
  await page.locator('#burgerMenuBtn').click();
  await page.setViewportSize({width:1440,height:900});
  await page.waitForFunction(()=>document.querySelector('#mobile-nav-panel').hidden);
  assert.equal(await page.locator('main').evaluate(e=>e.inert),false);
  await page.setViewportSize({width:390,height:844});
  await page.locator('#accessibility-toggle').click();
  await page.locator('[data-accessibility="larger"]').click();
  assert.equal(await page.locator('[data-accessibility="larger"]').getAttribute('aria-pressed'),'true');
  await page.locator('[data-accessibility="reset"]').click();
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#accessibility-panel').evaluate(e=>e.hidden),true);
  passed.push(route+': menu focus, branch, Escape, resize, accessibility options');
 }
 await page.locator('#theme-toggle').click();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.reload({waitUntil:'load'});
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.emulateMedia({colorScheme:'light'});
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.locator('#theme-toggle').click();
 assert.equal(await page.locator('html').evaluate(e=>getComputedStyle(e).colorScheme),'light only');
 passed.push('Theme preference persists and overrides system theme; light opts out of automatic darkening');
 await page.emulateMedia({forcedColors:'active'});
 await page.locator('#burgerMenuBtn').click();
 await page.screenshot({path:'output/responsive-audit/forced-colors-menu.png'});
 await page.keyboard.press('Escape');
 await context.close();
 const blocked=await browser.newContext({viewport:{width:320,height:740},colorScheme:'dark',serviceWorkers:'block'});
 await blocked.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:8765/')?r.continue():r.abort());
 await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Storage blocked','SecurityError');}}));
 const p=await blocked.newPage();await p.goto('http://127.0.0.1:8765/index.html',{waitUntil:'load'});
 await p.locator('#burgerMenuBtn').click();assert.equal(await p.locator('#mobile-nav-panel').evaluate(e=>e.hidden),false);
 passed.push('Navigation and theme initialize with storage blocked');
 await blocked.close();await browser.close();
 fs.writeFileSync('output/responsive-audit/interactions.json',JSON.stringify(passed,null,2));console.log(passed.join('\n'));
})().catch(e=>{console.error(e);process.exitCode=1;});
