name: Astro Quality Score

on:
  pull_request:
    branches: ["main"]

jobs:
  score:
    name: Calculate Astro Score
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Astro Score
        uses: Use-Astro/score-action@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-score-below: 70
          comment-on-pr: true
