name: Astro Doctor

on:
  pull_request:
    branches: ["main"]

jobs:
  doctor:
    name: Run Astro Doctor
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Astro Doctor
        uses: santi020k/astro-doctor@v1.0.1
        with:
          working-directory: "."
          fail-on: warning
          comment: true
          diff-only: true
