name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity."
          stale-pr-message: "This PR has been automatically marked as stale because it has not had recent activity."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
